name: Terraform Script CI
on:
  pull_request:
    branches: [ "main" ]
env:
  RELEASE_ID: "v${{ github.event.number }}"
  ARTIFACT_NAME: "v${{ github.event.number }}.zip"

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['dev', 'uat', 'prod']
    env:
      TF_ENV: ${{ matrix.environment }}

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: checkout code
        uses: actions/checkout@v2

      - name: terraform init
        id: terraform
        run: terraform init -input=false 

      - name: terraform plan
        id: terraform-plan
        run: terraform plan -input=false -lock=false


  generate-atifact:
    name: Generate Artifact
    needs: [plan]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: zip artifact
        run: zip ${RELEASE_ID}.zip -r . -x '.terraform/**' -x .terraform.lock.hcl -x '.git/**'

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RELEASE_ID }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: Disable EC2 metadata
        run: echo "export AWS_EC2_METADATA_DISABLED=true" >> $GITHUB_ENV

      - name: testing CI
        run: |
          pwd
          ls -la

      # - name: checkout code
      #   uses: actions/checkout@v2

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     aws-region: us-west-2

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      - name: upload artifact to S3
        run: 
          # aws s3 cp ${{ env.ARTIFACT_NAME }} s3://artifact-stores/${{ env.ARTIFACT_NAME }}
          aws s3 ls
