name: Deploy to Dev
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download artifact from S3
        run:
          aws s3 cp s3://tfstate-buckets/plan-${{ github.event.number }}.tfplan $GITHUB_WORKSPACE

      - name: Terraform apply
        id: terraform
        run: |
          terraform init
          terraform workspace new dev
          terraform workspace select dev
          terraform apply -auto-approve -state=plan-${{ github.event.number }}.tfplan
