name: Terraform Script CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Terraform Init and Plan
        id: terraform
        run: |
          terraform init -input=false
          terraform plan -out "plan-${{ github.event.number }}.tfplan"
