name: Deploy to PROD
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy to PROD
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download artifact from S3
        run:
          aws s3 cp s3://tfstate-buckets/terraform_plan.zip $GITHUB_WORKSPACE

      - name: Unzip the artifact
        run:
          unzip terraform_plan.zip

      - name: Terraform apply
        id: terraform
        run: |
          terraform init
          if ! terraform workspace select prod; then
            terraform workspace new prod; 
          else
            terraform workspace select prod
          fi
            terraform apply -auto-approve -state=plan-${{ github.event.number }}.tfplan
